spring.application.name=GestionPro

# ============================================================
# CONFIGURATION BASE DE DONNÉES POSTGRESQL
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_boutique
spring.datasource.username=gestionPro
spring.datasource.password=acim@2026
 
spring.datasource.driver-class-name=org.postgresql.Driver
 
# ============================================================
# JPA / HIBERNATE
# ============================================================
# create-drop : recrée les tables à chaque démarrage (pour le dev)
# update      : met à jour sans supprimer les données (recommandé après)
# validate    : vérifie sans modifier (production)
spring.jpa.hibernate.ddl-auto=update
 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
# ============================================================
# SERVEUR
# ============================================================
server.port=8080
 
# ============================================================
# CORS — autorise React (Vite tourne sur le port 5173)
# ============================================================
# Le CORS est géré dans CorsConfig.java

# UltraMsg WhatsApp
ultramsg.instance=instance173311
ultramsg.token=np9gwkq73lpb5vod
ultramsg.patron=+2250143410531
server.forward-headers-strategy=framework
#spring.main.allow-bean-definition-overriding=true

#jwt.secret=gestionProSecretKeyTresLongueEtSecurisee2026!!
#jwt.expiration=86400000

